site_name: Scadview Documentation
# site_name: "Meshsee Documentation"
watch: 
  - src
  - docs
  - CONTRIBUTING.md
  - LICENSE
docs_dir: docs
nav:
  - Home: index.md
  - About: about.md
  - Examples: examples.md
  - API Reference: api.md
  - Tutorials: tutorials.md
  - Contributing: contributing.md
  - License: license.md
theme: readthedocs
plugins:
  - include-markdown
  - search
  - macros:    # Jinja in markdown
      # include_dir: docs/includes   # optional, eg for macros
      verbose: false               # set true if you want debug info    
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
              docstring_style: google
              show_root_full_path: true
              show_root_heading: true
extra:
  project_name: Scadview
  package_name: scadview



