[project]
name = "meshsee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Neil Lamoureux", email = "neil.lamoureux@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "pyside6==6.*",
]

[project.scripts]
meshsee = "meshsee:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-mock>=3.14.0",
    "ruff>=0.9.2",
]
