[project]
name = "meshsee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Neil Lamoureux", email = "neil.lamoureux@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "manifold3d==3.*",
    "matplotlib>=3.10.3",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.15",
    "mkdocstrings-python>=1.16.12",
    "moderngl>=5.12.0",
    "networkx>=3.5",
    "numpy==2.*",
    "pillow>=11.2.1",
    "pyright>=1.1.401",
    "pyrr>=0.10.3",
    "pyside6==6.*",
    "shapely>=2.1.1",
    "trimesh>=4.6.1",
]

[project.scripts]
meshsee = "meshsee:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "meshsee",
    "pytest>=8.3.4",
    "pytest-cov>=6.1.1",
    "pytest-mock>=3.14.0",
    "ruff>=0.9.2",
]

[tool.uv.sources]
meshsee = { workspace = true }
