name: CI Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x ./scripts/*.sh; ls -l ./scripts

      # - name: Install GTK+ 2 development files (for wx)
      #   run: sudo apt-get update && sudo apt-get install -y libgtk2.0-dev
      
      - name: Install wx dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev pkg-config
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Install uv 
        uses: astral-sh/setup-uv@v1
      
      - name: Install dependencies
        run: |
          URL=https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04
          PIP_FIND_LINKS=$URL UV_NO_BUILD=1 uv sync --frozen

      - name: Run formatter check
        run: uv run ./scripts/format.sh --check

      - name: Run linter
        run: uv run ./scripts/lint.sh

      - name: Run type checker
        run: uv run ./scripts/type.sh

      - name: Run tests
        run: uv run ./scripts/test.sh --ignore=tests/ui
