name: CI Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x ./scripts/*.sh; ls -l ./scripts

      # - name: Install GTK+ 2 development files (for wx)
      #   run: sudo apt-get update && sudo apt-get install -y libgtk2.0-dev
      
      - name: Install wx dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev pkg-config
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock', 'pyproject.toml') }}-${{ matrix.python-version }}

      - name: Install uv 
        uses: astral-sh/setup-uv@v1
      
      - name: Install dependencies without wxpython
        run: |
          uv sync --frozen --no-install-package wxpython


      - name: Run formatter check
        run: uv run ./scripts/format.sh --check

      - name: Run linter
        run: uv run ./scripts/lint.sh

      - name: Run type checker
        run: uv run ./scripts/type.sh

      - name: Run tests
        run: uv run ./scripts/test.sh --ignore=tests/ui
