name: CI Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Install uv
        uses: supplypike/setup-bin@v3
        with:
          uri: https://github.com/astral-sh/uv/releases/latest/download/uv-x86_64-unknown-linux-gnu.tar.gz
          name: uv
          version: latest

      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      - name: Install dependencies
        run: |
          uv sync --system

      - name: Run formatter check
        run: ./scripts/format.sh

      - name: Run linter
        run: ./scripts/lint.sh

      - name: Run type checker
        run: ./scripts/typecheck.sh

      - name: Run tests
        run: ./scripts/test.sh
